/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTutoriaisRouteImport } from './routes/_authenticated/tutoriais'
import { Route as AuthenticatedScriptsRouteImport } from './routes/_authenticated/scripts'
import { Route as AuthenticatedProblemasRouteImport } from './routes/_authenticated/problemas'
import { Route as AuthenticatedPrecosRouteImport } from './routes/_authenticated/precos'
import { Route as AuthenticatedConhecimentoRouteImport } from './routes/_authenticated/conhecimento'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutoriaisRoute = AuthenticatedTutoriaisRouteImport.update({
  id: '/tutoriais',
  path: '/tutoriais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScriptsRoute = AuthenticatedScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProblemasRoute = AuthenticatedProblemasRouteImport.update({
  id: '/problemas',
  path: '/problemas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrecosRoute = AuthenticatedPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConhecimentoRoute =
  AuthenticatedConhecimentoRouteImport.update({
    id: '/conhecimento',
    path: '/conhecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/conhecimento': typeof AuthenticatedConhecimentoRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/problemas': typeof AuthenticatedProblemasRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/tutoriais': typeof AuthenticatedTutoriaisRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/conhecimento': typeof AuthenticatedConhecimentoRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/problemas': typeof AuthenticatedProblemasRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/tutoriais': typeof AuthenticatedTutoriaisRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRoute
  '/_authenticated/conhecimento': typeof AuthenticatedConhecimentoRoute
  '/_authenticated/precos': typeof AuthenticatedPrecosRoute
  '/_authenticated/problemas': typeof AuthenticatedProblemasRoute
  '/_authenticated/scripts': typeof AuthenticatedScriptsRoute
  '/_authenticated/tutoriais': typeof AuthenticatedTutoriaisRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/assistente'
    | '/conhecimento'
    | '/precos'
    | '/problemas'
    | '/scripts'
    | '/tutoriais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/assistente'
    | '/conhecimento'
    | '/precos'
    | '/problemas'
    | '/scripts'
    | '/tutoriais'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/assistente'
    | '/_authenticated/conhecimento'
    | '/_authenticated/precos'
    | '/_authenticated/problemas'
    | '/_authenticated/scripts'
    | '/_authenticated/tutoriais'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutoriais': {
      id: '/_authenticated/tutoriais'
      path: '/tutoriais'
      fullPath: '/tutoriais'
      preLoaderRoute: typeof AuthenticatedTutoriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts': {
      id: '/_authenticated/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AuthenticatedScriptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problemas': {
      id: '/_authenticated/problemas'
      path: '/problemas'
      fullPath: '/problemas'
      preLoaderRoute: typeof AuthenticatedProblemasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precos': {
      id: '/_authenticated/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof AuthenticatedPrecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conhecimento': {
      id: '/_authenticated/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof AuthenticatedConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRoute
  AuthenticatedConhecimentoRoute: typeof AuthenticatedConhecimentoRoute
  AuthenticatedPrecosRoute: typeof AuthenticatedPrecosRoute
  AuthenticatedProblemasRoute: typeof AuthenticatedProblemasRoute
  AuthenticatedScriptsRoute: typeof AuthenticatedScriptsRoute
  AuthenticatedTutoriaisRoute: typeof AuthenticatedTutoriaisRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRoute,
  AuthenticatedConhecimentoRoute: AuthenticatedConhecimentoRoute,
  AuthenticatedPrecosRoute: AuthenticatedPrecosRoute,
  AuthenticatedProblemasRoute: AuthenticatedProblemasRoute,
  AuthenticatedScriptsRoute: AuthenticatedScriptsRoute,
  AuthenticatedTutoriaisRoute: AuthenticatedTutoriaisRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
