/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTutoriaisRouteImport } from './routes/_authenticated/tutoriais'
import { Route as AuthenticatedTreinamentosRouteImport } from './routes/_authenticated/treinamentos'
import { Route as AuthenticatedSugestoesRouteImport } from './routes/_authenticated/sugestoes'
import { Route as AuthenticatedScriptsRouteImport } from './routes/_authenticated/scripts'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedProblemasRouteImport } from './routes/_authenticated/problemas'
import { Route as AuthenticatedPrecosRouteImport } from './routes/_authenticated/precos'
import { Route as AuthenticatedMeusRelatoriosRouteImport } from './routes/_authenticated/meus-relatorios'
import { Route as AuthenticatedCrmProspeccaoRouteImport } from './routes/_authenticated/crm-prospeccao'
import { Route as AuthenticatedCrmLeadsRouteImport } from './routes/_authenticated/crm-leads'
import { Route as AuthenticatedConhecimentoRouteImport } from './routes/_authenticated/conhecimento'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicKnowledgeFileRouteImport } from './routes/api/public/knowledge-file'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutoriaisRoute = AuthenticatedTutoriaisRouteImport.update({
  id: '/tutoriais',
  path: '/tutoriais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreinamentosRoute =
  AuthenticatedTreinamentosRouteImport.update({
    id: '/treinamentos',
    path: '/treinamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSugestoesRoute = AuthenticatedSugestoesRouteImport.update({
  id: '/sugestoes',
  path: '/sugestoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScriptsRoute = AuthenticatedScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProblemasRoute = AuthenticatedProblemasRouteImport.update({
  id: '/problemas',
  path: '/problemas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrecosRoute = AuthenticatedPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusRelatoriosRoute =
  AuthenticatedMeusRelatoriosRouteImport.update({
    id: '/meus-relatorios',
    path: '/meus-relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmProspeccaoRoute =
  AuthenticatedCrmProspeccaoRouteImport.update({
    id: '/crm-prospeccao',
    path: '/crm-prospeccao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmLeadsRoute = AuthenticatedCrmLeadsRouteImport.update({
  id: '/crm-leads',
  path: '/crm-leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConhecimentoRoute =
  AuthenticatedConhecimentoRouteImport.update({
    id: '/conhecimento',
    path: '/conhecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicKnowledgeFileRoute = ApiPublicKnowledgeFileRouteImport.update({
  id: '/api/public/knowledge-file',
  path: '/api/public/knowledge-file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/conhecimento': typeof AuthenticatedConhecimentoRoute
  '/crm-leads': typeof AuthenticatedCrmLeadsRoute
  '/crm-prospeccao': typeof AuthenticatedCrmProspeccaoRoute
  '/meus-relatorios': typeof AuthenticatedMeusRelatoriosRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/problemas': typeof AuthenticatedProblemasRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/sugestoes': typeof AuthenticatedSugestoesRoute
  '/treinamentos': typeof AuthenticatedTreinamentosRoute
  '/tutoriais': typeof AuthenticatedTutoriaisRoute
  '/api/public/knowledge-file': typeof ApiPublicKnowledgeFileRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/conhecimento': typeof AuthenticatedConhecimentoRoute
  '/crm-leads': typeof AuthenticatedCrmLeadsRoute
  '/crm-prospeccao': typeof AuthenticatedCrmProspeccaoRoute
  '/meus-relatorios': typeof AuthenticatedMeusRelatoriosRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/problemas': typeof AuthenticatedProblemasRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/sugestoes': typeof AuthenticatedSugestoesRoute
  '/treinamentos': typeof AuthenticatedTreinamentosRoute
  '/tutoriais': typeof AuthenticatedTutoriaisRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/knowledge-file': typeof ApiPublicKnowledgeFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRoute
  '/_authenticated/conhecimento': typeof AuthenticatedConhecimentoRoute
  '/_authenticated/crm-leads': typeof AuthenticatedCrmLeadsRoute
  '/_authenticated/crm-prospeccao': typeof AuthenticatedCrmProspeccaoRoute
  '/_authenticated/meus-relatorios': typeof AuthenticatedMeusRelatoriosRoute
  '/_authenticated/precos': typeof AuthenticatedPrecosRoute
  '/_authenticated/problemas': typeof AuthenticatedProblemasRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/scripts': typeof AuthenticatedScriptsRoute
  '/_authenticated/sugestoes': typeof AuthenticatedSugestoesRoute
  '/_authenticated/treinamentos': typeof AuthenticatedTreinamentosRoute
  '/_authenticated/tutoriais': typeof AuthenticatedTutoriaisRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/knowledge-file': typeof ApiPublicKnowledgeFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/assistente'
    | '/conhecimento'
    | '/crm-leads'
    | '/crm-prospeccao'
    | '/meus-relatorios'
    | '/precos'
    | '/problemas'
    | '/ranking'
    | '/scripts'
    | '/sugestoes'
    | '/treinamentos'
    | '/tutoriais'
    | '/api/public/knowledge-file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/assistente'
    | '/conhecimento'
    | '/crm-leads'
    | '/crm-prospeccao'
    | '/meus-relatorios'
    | '/precos'
    | '/problemas'
    | '/ranking'
    | '/scripts'
    | '/sugestoes'
    | '/treinamentos'
    | '/tutoriais'
    | '/'
    | '/api/public/knowledge-file'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/assistente'
    | '/_authenticated/conhecimento'
    | '/_authenticated/crm-leads'
    | '/_authenticated/crm-prospeccao'
    | '/_authenticated/meus-relatorios'
    | '/_authenticated/precos'
    | '/_authenticated/problemas'
    | '/_authenticated/ranking'
    | '/_authenticated/scripts'
    | '/_authenticated/sugestoes'
    | '/_authenticated/treinamentos'
    | '/_authenticated/tutoriais'
    | '/_authenticated/'
    | '/api/public/knowledge-file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicKnowledgeFileRoute: typeof ApiPublicKnowledgeFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutoriais': {
      id: '/_authenticated/tutoriais'
      path: '/tutoriais'
      fullPath: '/tutoriais'
      preLoaderRoute: typeof AuthenticatedTutoriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinamentos': {
      id: '/_authenticated/treinamentos'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof AuthenticatedTreinamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sugestoes': {
      id: '/_authenticated/sugestoes'
      path: '/sugestoes'
      fullPath: '/sugestoes'
      preLoaderRoute: typeof AuthenticatedSugestoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts': {
      id: '/_authenticated/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AuthenticatedScriptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problemas': {
      id: '/_authenticated/problemas'
      path: '/problemas'
      fullPath: '/problemas'
      preLoaderRoute: typeof AuthenticatedProblemasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precos': {
      id: '/_authenticated/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof AuthenticatedPrecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-relatorios': {
      id: '/_authenticated/meus-relatorios'
      path: '/meus-relatorios'
      fullPath: '/meus-relatorios'
      preLoaderRoute: typeof AuthenticatedMeusRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm-prospeccao': {
      id: '/_authenticated/crm-prospeccao'
      path: '/crm-prospeccao'
      fullPath: '/crm-prospeccao'
      preLoaderRoute: typeof AuthenticatedCrmProspeccaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm-leads': {
      id: '/_authenticated/crm-leads'
      path: '/crm-leads'
      fullPath: '/crm-leads'
      preLoaderRoute: typeof AuthenticatedCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conhecimento': {
      id: '/_authenticated/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof AuthenticatedConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/knowledge-file': {
      id: '/api/public/knowledge-file'
      path: '/api/public/knowledge-file'
      fullPath: '/api/public/knowledge-file'
      preLoaderRoute: typeof ApiPublicKnowledgeFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRoute
  AuthenticatedConhecimentoRoute: typeof AuthenticatedConhecimentoRoute
  AuthenticatedCrmLeadsRoute: typeof AuthenticatedCrmLeadsRoute
  AuthenticatedCrmProspeccaoRoute: typeof AuthenticatedCrmProspeccaoRoute
  AuthenticatedMeusRelatoriosRoute: typeof AuthenticatedMeusRelatoriosRoute
  AuthenticatedPrecosRoute: typeof AuthenticatedPrecosRoute
  AuthenticatedProblemasRoute: typeof AuthenticatedProblemasRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedScriptsRoute: typeof AuthenticatedScriptsRoute
  AuthenticatedSugestoesRoute: typeof AuthenticatedSugestoesRoute
  AuthenticatedTreinamentosRoute: typeof AuthenticatedTreinamentosRoute
  AuthenticatedTutoriaisRoute: typeof AuthenticatedTutoriaisRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRoute,
  AuthenticatedConhecimentoRoute: AuthenticatedConhecimentoRoute,
  AuthenticatedCrmLeadsRoute: AuthenticatedCrmLeadsRoute,
  AuthenticatedCrmProspeccaoRoute: AuthenticatedCrmProspeccaoRoute,
  AuthenticatedMeusRelatoriosRoute: AuthenticatedMeusRelatoriosRoute,
  AuthenticatedPrecosRoute: AuthenticatedPrecosRoute,
  AuthenticatedProblemasRoute: AuthenticatedProblemasRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedScriptsRoute: AuthenticatedScriptsRoute,
  AuthenticatedSugestoesRoute: AuthenticatedSugestoesRoute,
  AuthenticatedTreinamentosRoute: AuthenticatedTreinamentosRoute,
  AuthenticatedTutoriaisRoute: AuthenticatedTutoriaisRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicKnowledgeFileRoute: ApiPublicKnowledgeFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
